spring:
  application:
    name: erp-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/erp-db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
