spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp-db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

logging:
  level:
    root: INFO
